on: [push]

jobs:
  vault_updater_job:
    runs-on: ubuntu-latest
    name: A job to update all vaults' amounts.
    steps:
      - name: Vault Updater
        id: vault-updater
        uses: heavy-duty/drill-vault-updater-action@v1.0.7
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          rpc-endpoint: ${{ secrets.RPC_ENDPOINT }}
          program-id: ${{ secrets.PROGRAM_ID }}
          drill-bot-id: ${{ secrets.DRILL_BOT_ID }}
          github-repository: ${{ github.repository }}
          cluster: ${{ secrets.CLUSTER }}
      - name: Get Result
        run: echo "The result was ${{ steps.vault-updater.result }}"
